version: "3"
services:
    www:
        image: node:8
        volumes:
            - ./:/app
        working_dir: /app
        command: ['npm', 'run', 'docs:dev']
        ports:
            - 8001:8001
            - 8002:8002